"""add fulfillment source to blood requests

Revision ID: 2fa68a632cbc
Revises: 24ffb196a2c1
Create Date: 2026-09-01 22:44:27.305988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fa68a632cbc'
down_revision = '24ffb196a2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_email'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfillment_source', sa.String(length=50), nullable=True))

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('blood_requests', schema=None) as batch_op:
        batch_op.drop_column('fulfillment_source')

    op.create_table('email_verifications',
    sa.Column('verification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('otp_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('purpose', mysql.ENUM('verify', 'reset'), server_default=sa.text("'verify'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('email_verifications_ibfk_1')),
    sa.PrimaryKeyConstraint('verification_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_email'), ['email'], unique=False)

    # ### end Alembic commands ###
